<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonCURDOperation\CommonCURDOperation.csproj" />
    <ProjectReference Include="..\DTOModelsShared\DTOModelsShared.csproj" />
    <ProjectReference Include="..\UtilityShared\UtilityShared.csproj" />
  </ItemGroup>

</Project>
